### ISSUE TITLE
Add the version of the OS or the libraries to the header of text rendering reports

### ISSUE THREAD

**Issue by miguelsousa** [unicode-org/text-rendering-tests#27]
I think it would be valuable if the text rendering reports had information about the specific version of the OS (in the case of [CoreText](https://raw.githack.com/unicode-org/text-rendering-tests/master/reports/CoreText.html)) or the libraries (in the case of [FreeStack](https://raw.githack.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html)) that were used when the report was generated. For the FreeStack it may be necessary to reference a specific commit hash, in case a new build of a given library wasn't available at the time.

**Comment by HinTak** [comment]
I think I might be asking for a similar thing - the minimum upgrade to pass a test, for the freestack. Over the weekend, I tried modifying it to just use the system libraries (instead of building from submodules). I was surprised two more of the tests failed, compared to building from the submodules. Considering I have freetype 2.8. One of the tests were shaping related, so not using the latest harfbuzz and failing seems reasonable, but the other was CFF2-1, which I thought should depend on freetype only, since it is about getting a glyph. But it also needs the latest harfbuzz for some not-obvious reason.

Also I am not sure what's purpose of testing builds from submodules - yes, it is nice that the latest code passes, and there is no regressions, but most dintros are about a year or two behind, at least. And people don't upgrade important libraries like these unless there is a reason to, or as part of a full scale system upgrade. Hence the minimum version update idea.

**Comment by HinTak** [comment]
I bisected the harfbuzz change to between 1.3.4 and 1.3.4-53-g805f76f but most of the middle are very broken and won't build. Anyway, I looked at the changelog of harfbuzz and 1.4.0 is the one which adds font variations, so it is just as well.
