### ISSUE TITLE
font-parsing tests?

### ISSUE THREAD

**Issue by Pomax** [unicode-org/text-rendering-tests#63]
A few folks and myself have recently been working on getting [Font.js](https://github.com/Pomax/Font.js) uplifted to ES2020 and browser+node compatibility, but it's hard to come by dedicated fonts for testing things like detecting the correct number of GPOS/GSUB script/feature/lookups, ligature resolution, non cmap-4/12 character support, fvar, etc.

Is there a subset of this battery of fonts that might work well for the purpose of not specifically text _rendering_, but certainly doing everything up to the shaping step?

**Comment by brawer** [comment]
Because all the [engines currently being tested](https://github.com/unicode-org/text-rendering-tests#supported-platforms) can return glyph outlines, the current test harness is always comparing paths, even if the test case (and the corresponding test font) is actually about an earlier step. For your purpose, maybe you could go manually over the [description of the test suite](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html) and decide which specific tests make sense for you? For example, I’d imagine that the `CMAP` tests might be useful, but those for `GPOS` will probably be irrelevant for Font.js unless you change the scope of your project to include shaping. Even if you don’t care about shaping, have a look at the [HarfBuzz test suite](https://github.com/harfbuzz/harfbuzz/tree/master/test/shaping/data/text-rendering-tests) which takes the test fonts from this repo here, and [automatically converts them](https://github.com/harfbuzz/harfbuzz/blob/master/test/shaping/data/text-rendering-tests/update.py#L27) to the format used in the HarfBuzz test suite; maybe Font.js could do something similar? — Also, please feel (extremely!) welcome to contribute additional test fonts to this test suite!

**Comment by Pomax** [comment]
Great suggestions, thanks! If we do end up crafting custom fonts for testing and validation purposes, I'll be sure to let you know/contribute them via PR.

**Comment by HinTak** [comment]
If you are looking for some broken fonts, https://github.com/google/oss-fuzz makea some for their freetype fuzz'ing. They may not be broken in the way you want though...

**Comment by Pomax** [comment]
Font.js doesn't really do any validation, it's more for parsing fonts that you are assumed to have made sure are not broken already. Still, good to know there's a resource for broken fonts, too!
